# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a30d12a9257400fbd085bfd8b53922cb81ade57cf9e8bdff47eb2effc1e950503e150e8664c1915b812639eeccfa87604c4eac821fb675a889f03f751d51d31

test:
  secret_key_base: b96b1c5eb495f7f7a704a4673ac7a24bf4512c6f494cd8f33efb7a7bb24af17a1c8821749d9859e6b3e6ed93a4610ca3ac53998635e4797e004521bc2bf1ab55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
